### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Upasna55** [arun-sub/genomicsbench#11]
Hello All

I am getting the following error while executing `make`:

![Screenshot from 2022-09-11 09-28-09](https://user-images.githubusercontent.com/91068864/189511823-6dfa91db-c214-4af7-ac1f-a2b6b94e9538.png)

`gcc -v` for bug info gives the following output:

![Screenshot from 2022-09-11 09-34-10](https://user-images.githubusercontent.com/91068864/189511891-d9aec213-adb5-45c9-a857-8b583c85537d.png)

I would be so grateful for any help in building `genomicsbench` successfully. 

Thanks & Regards
Upasna

**Comment by arun-sub** [comment]
Thanks for reporting this. I fixed some issue related to GKL in the latest commit to master. Could you check if that solves the issue ? If not, could you try compiling with an older version of gcc (e.g., gcc-7).

--Arun

**Comment by Upasna55** [comment]
Thanks a lot, it resolves the issue.

Best Regards
Upasna
