### ISSUE TITLE
Input data for scripts/run-cpu.sh

### ISSUE THREAD

**Issue by phridley** [arun-sub/genomicsbench#3]
Hi,

just running the cpu benchmarks and noticed that for the file names for the current version of input-datasets.tar.gz seem to be wrong. Please could you check, I think

../benchmarks/bsw/bsw -pairs $INPUTS_DIR/bsw/large/banded_SRR7733443_1m_input.txt -t 1 -b 512

should be

../benchmarks/bsw/bsw -pairs $INPUTS_DIR/bsw/large/bandedSWA_SRR7733443_1m_input.txt -t 1 -b 512

and

../benchmarks/bsw/bsw -pairs $INPUTS_DIR/bsw/small/banded_SRR7733443_100k_input.txt -t 1 -b 512

should be

../benchmarks/bsw/bsw -pairs $INPUTS_DIR/bsw/small/bandedSWA_SRR7733443_100k_input.txt -t 1 -b 512

Thanks

**Comment by arun-sub** [comment]
Thanks for bringing this up. I fixed the script now.

--Arun

**Comment by phridley** [comment]
That's great. Thanks.
